language: node_js
node_js:
- '6'
sudo: false
notifications:
  slack:
    secure: cfLZGjI1is5/5mFAkY5jeftbg71HNBJJ0vs7wQxFW37UFMPuTHvxhilzUsSEiDG846bzbOEz/wrbvuqdfKDkvBxFOcJzPru62UExzO80eBlQMpA05FcCMWNxm0JCQZpZW6AG5wxXd1XNAxyKYoqXCeOoxgLAurmVCrxcxqw+XS7Sj/fsKWSJBLOOE8tgr8hBtZfDHMHKI3MA49RN3FLda72nqz6kRZLP1Li9Y8WM3/d4EOzOoIcpgPnh5PoezaBsqAwbePlIY4+yezQar8Bt1suF0DYk6IOSXT4CEWrTpQKESPgQdCO6RfEL8c+EnN08TKm7UK3bBHuACaHCBwlZE2ZEmeq0IDZ6uhC9ZQIBovQShLOO40+IAsJPH/bI5YD3cujeKus2jwgsMitoaoR7umLoZu6qIs8LF1bM4ylusMQCEFVaL9dlF7SU+rIvp/HeJkkKUkFYULcMHT6kGyi+sjuthwS0IjwYMssFOK+zKlipemca3g1GFaoodONTpCknO40De4epk+6bAT15crKhY07/6wmaeP80sokIARm+fOIsT1yb9fJt4mqOAhDrdTMUq9j73k8Mpbsd7i3g8pIcVgNG4IoPGgv+UqIvjFH5+faa3StsIpJGNQPEHNmzFKgZaGuuq6AkGdq5RASHa/XgiuHutddtMDZgnFlRfY9ZZK4=
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch:
    - master
cache:
  directories:
  - node_modules
