language: php
php:
  - '5.6'
script:
  - echo "No tests available"
notifications:
  slack:
    secure: MMr+dNeNuTY8PJgCaaSBdBZwyHWWftDsk7vaDEkQEe4Amir4CWD9o+FFajzYJ0vfUAN21sIgmoRqnSWyngZlARtROc+p2PMMjlTWFidGhMHhNPVHxkneW2PkNk9u70y8TnDl5ptLho4kzLT81o/aRAmPrAfPcZStwV2iq66TyNk2yJ2biyWlC0eSfHKBd4nUjixIlcK979V9ahc/h6eqjEr+Q4WKqFOv48N5hoc/6GE8OVqlJqdwZ8kWPAx+CDsweg5ezyMqRODIvDe0vcGqRRzNPzPD5wISdy8jwEq+ZOmWJNn719fqnqJABWknlqLcoOkeNeEu++m7nbs+fURJJjbl3fc8lFgGDKptSG+uOxZxTywsL1/4uwxrspmn+wckP5tkOyOdM50XWu5L1k1Q3lAi3iMsXjlzgMlFRqHMy+iYF0VxtQqqqJMRgMuv+rRZdqRO+Ml3aa2ckDciwXnuRPzTaoQ4XYMfwYtthWwfcayKr1SlAz4pwUEDR4mrta3Qh7Q1HCdNtGLI8FIdb4MHwhmZFWLNfXsQuxhydE2FR0uSg5Ca0mJuWdGCDKqgnOkpOFUFmwtQ67EA+qtSrzpZrawwiRpONpYMF+lTHomYbZOAbPjG77+QgPR87/x77BiP8xuY72RyvPGVIo2ff2MLTZxSoboKsLoqi7PAFU01Bwg=
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch:
      - master
