version: '2'

services:
  fpm:
    volumes:
     - ./:/var/www/html/
     - ./.data/vendor:/var/www/html/vendor
  nginx:
    volumes:
     - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
  frontend-dev:
    image: blindernuka/billett-frontend
    build: billett-frontend
    volumes:
     - ./billett-frontend:/usr/src/app
     - ./.data/node_modules:/usr/src/app/node_modules
    command: /dev.sh
