version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: blindernuka/billett-backend
    environment:
      SIMPLESAMLPHP_ADMINPASS: billett
      SIMPLESAMLPHP_SECRETSALT: replace-this-in-other-envs
      LARAVEL_ENV: local
      BILLETT_KEY: KeNd439jeX9n9hqudOxXqCQErFmbApoi
      BILLETT_MYSQL_PASS: uka_billett
  nginx:
    image: nginx:stable-alpine
    ports:
     - "8081:80"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./.data/billett-frontend-dist:/var/www/billett-frontend-dist/
    volumes_from:
     - fpm:ro
  database:
    image: mysql:5.6
    volumes:
      - ./.data/db/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: uka
      MYSQL_DATABASE: uka_billett
      MYSQL_USER: uka_billett
      MYSQL_PASSWORD: uka_billett
