version: '2'

services:
  fpm:
    volumes:
     - ./backend/:/var/www/html/
    command: /dev.sh
  database:
    image: mysql:5.6
    volumes:
      - ./.data/db/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: uka
      MYSQL_DATABASE: uka_billett
      MYSQL_USER: uka_billett
      MYSQL_PASSWORD: uka_billett
