version: '2'

services:
  fpm:
    volumes:
     - ./src/:/var/www/html/
    command: /dev.sh
  nginx:
    volumes:
     - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
  frontend-dev:
    image: blindernuka/billett-frontend
    build: billett-frontend
    volumes:
     - ./billett-frontend:/usr/src/app
     - ./.data/node_modules:/usr/src/app/node_modules
    command: /dev.sh
  database:
    image: mysql:5.6
    volumes:
      - ./.data/db/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: uka
      MYSQL_DATABASE: uka_billett
      MYSQL_USER: uka_billett
      MYSQL_PASSWORD: uka_billett
