version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    image: blindernuka/billett-backend
    environment:
      SIMPLESAMLPHP_ADMINPASS: billett
      SIMPLESAMLPHP_SECRETSALT: replace-this-in-other-envs
      LARAVEL_ENV: local
      BILLETT_KEY: KeNd439jeX9n9hqudOxXqCQErFmbApoi
      BILLETT_MYSQL_PASS: uka_billett
      DIBS_HMAC_KEY: overridden-in-local-configuration
    env_file:
      - backend/.env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: blindernuka/billett-proxy
    ports:
     - "8081:80"
    volumes_from:
     - fpm:ro
    environment:
      FPM_HOST: fpm:9000
      FRONTEND_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
