name: autofix.ci # needed to securely identify the workflow
on:
  pull_request:
jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          package_json_file: frontend/package.json
      - run: pnpm install
        working-directory: frontend
      - run: pnpm run lint --fix
        working-directory: frontend
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
