name: backend
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/backend.yml"
      - "backend/**"
      - "nginx/**"
      - "simplesamlphp/**"
      - "Dockerfile*"
jobs:
  phpunit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: "8.5"
          extensions: mbstring, gd
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          working-directory: backend
          composer-options: "--ignore-platform-req=ext-opentelemetry --no-scripts"

      - name: Run PHPUnit
        working-directory: backend
        run: vendor/bin/phpunit

  backend:
    runs-on: ubuntu-latest
    needs: phpunit
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nginx container
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: Dockerfile.nginx
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build fpm container
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: Dockerfile.fpm
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push nginx container
        id: nginx_docker_build
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: ghcr.io/blindern/billett-proxy:latest

      - name: Push fpm container
        id: fpm_docker_build
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: Dockerfile.fpm
          push: true
          tags: ghcr.io/blindern/billett-backend:latest

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -sS -i -N -L -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST "https://deployer.foreningenbs.no/deploy?stream" -d '
          {
            "service": "uka-billett",
            "attributes": {
              "fpm_image": "ghcr.io/blindern/billett-backend@${{ steps.fpm_docker_build.outputs.digest }}",
              "proxy_image": "ghcr.io/blindern/billett-proxy@${{ steps.nginx_docker_build.outputs.digest }}"
            }
          }' | tee /tmp/deploy-output.txt
          tail -1 /tmp/deploy-output.txt | grep -q "DEPLOY OK"
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}

  e2e-tests:
    if: github.ref == 'refs/heads/main'
    needs: backend
    permissions:
      contents: read
    uses: ./.github/workflows/run-e2e-tests.yml
    with:
      tag: "@api"
    secrets: inherit
