name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build nginx container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nginx
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build fpm container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.fpm
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push nginx container
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nginx
          tags: blindernuka/billett-proxy:latest

      - name: Push fpm container
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.fpm
          tags: blindernuka/billett-backend:latest
